# .github/workflows/main.yml
name: Build & Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
#  schedule:
#    - cron: '30 5 * * 5'

jobs:

  build:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
#    - name: Select Xcode 16.2
#      run: sudo xcode-select -s "/Applications/Xcode_16.2.app"
    - name: Show buildable schemes
      run: xcodebuild -list -project ./mov2gif.xcodeproj
    - uses: mxcl/xcodebuild@v3
      with:
        platform: macOS
        scheme: 'Convertor'
        action: build
#        working-directory: ./DarkModeDiscovery
        verbosity: xcpretty
        upload-logs: always
        configuration: Release

  unit-tests:
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
#    - name: SwiftLint
#        run: brew link --overwrite swiftlint || brew install swiftlint
#    - name: Select Xcode 16.2
#      run: sudo xcode-select -s "/Applications/Xcode_16.2.app"
    - name: Show buildable schemes
      run: xcodebuild -list -project ./mov2gif.xcodeproj
    - uses: mxcl/xcodebuild@v3
      with:
        platform: macOS
        scheme: 'Convertor'
        action: test
#        working-directory: ./DarkModeDiscovery
        verbosity: xcpretty
        upload-logs: always
        configuration: Release
